### ISSUE TITLE
Cannot call asyncio.run on client.get_page

### ISSUE THREAD

**Issue by Dauriel** [euirim/goodwiki#1]
Is there a way to run the template on a jupyter notebook? I try running 
```
import asyncio
from goodwiki import GoodwikiClient

client = GoodwikiClient()
page = asyncio.run(client.get_page("Usain Bolt"))
print(page)
```

And get the following error:
```
RuntimeError: asyncio.run() cannot be called from a running event loop
```
(Code works on .py)

**Comment by euirim** [comment]
Jupyter doesn't support asyncio, but you should be able to do without it in Jupyterlab. Could you try executing the statement directly in the notebook without using `asyncio.run`? Basically:

```python
page = await client.get_page("Usain Bolt")
```

**Comment by Dauriel** [comment]
Yes, everything works great outside of Jupyterlab

**Comment by euirim** [comment]
> Jupyter doesn't support asyncio, but you should be able to do without it in Jupyterlab. Could you try executing the statement directly in the notebook without using `asyncio.run`? Basically:
> 
> ```python
> page = await client.get_page("Usain Bolt")
> ```

Does the code snippet here work for you in Jupyterlab? You should be able to use `await` directly in a Jupyterlab cell without needing `asyncio.run`.

You can see how I used it in this Jupyterlab notebook: https://github.com/euirim/goodwiki/blob/main/notebooks/client_testing.ipynb

**Comment by euirim** [comment]
You can see how I used it in this Jupyterlab notebook: https://github.com/euirim/goodwiki/blob/main/notebooks/client_testing.ipynb

**Comment by Dauriel** [comment]
Perfect, thanks!
